#############################################################################
# Makefile for building: SDMed
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  PruebasInterfazObra.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -config release -o Makefile PruebasInterfazObra.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -std=c++1y -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = SDMed1.0.0
DISTDIR = /home/david/programacion/cmasmas/PruebasInterfazObra/.tmp/SDMed1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Editor/editor.cpp \
		Modelos/PrincipalModel.cpp \
		Calc/src/Calc.cpp \
		src/Certificacion.cpp \
		src/Concepto.cpp \
		src/Datos.cpp \
		src/Fecha.cpp \
		src/GestorEntradaDatosLineasMedicion.cpp \
		src/LineaMedicion.cpp \
		src/MedCert.cpp \
		src/Medicion.cpp \
		src/Obra.cpp \
		src/Precio.cpp \
		src/Redondeos.cpp \
		src/Unidades.cpp \
		src/Codificacion.cpp \
		filter.cpp \
		Tablas/tablamedcert.cpp \
		Delegados/delegadocolumnasbloqueadas.cpp \
		Tablas/tablaprincipal.cpp \
		iconos.cpp \
		Delegados/delegadoiconos.cpp \
		Tablas/tablabase.cpp \
		Dialogos/dialogosuprimirmedicion.cpp \
		Dialogos/dialogoprecio.cpp \
		Delegados/delegadobase.cpp \
		mainwindow.cpp \
		Dialogos/dialogodatoscodigoresumen.cpp \
		Dialogos/dialogonuevacertificacion.cpp \
		Modelos/MedCertModel.cpp \
		Undo/undomedicion.cpp \
		Undo/undoeditarprincipal.cpp \
		Editor/micustomtextedit.cpp \
		Delegados/delegadonumerosbase.cpp \
		Delegados/delegadonumerostablaprincipal.cpp \
		Delegados/delegadonumerostablamedcert.cpp \
		Dialogos/dialogoabout.cpp \
		Dialogos/dialogocreditos.cpp \
		Dialogos/dialogoajustarprecio.cpp \
		Undo/undoajustarpresupuesto.cpp \
		Dialogos/dialogolicencia.cpp \
		instancia.cpp \
		Ficheros/abrirguardarseg.cpp \
		Ficheros/abrirguardarbc3.cpp \
		Ficheros/abrirguardar.cpp qrc_iconosEditor.cpp \
		qrc_iconos.cpp \
		qrc_recursos.cpp \
		moc_editor.cpp \
		moc_filter.cpp \
		moc_tablamedcert.cpp \
		moc_delegadocolumnasbloqueadas.cpp \
		moc_tablaprincipal.cpp \
		moc_tablabase.cpp \
		moc_dialogosuprimirmedicion.cpp \
		moc_dialogoprecio.cpp \
		moc_delegadobase.cpp \
		moc_mainwindow.cpp \
		moc_dialogodatoscodigoresumen.cpp \
		moc_PrincipalModel.cpp \
		moc_dialogonuevacertificacion.cpp \
		moc_MedCertModel.cpp \
		moc_micustomtextedit.cpp \
		moc_dialogoabout.cpp \
		moc_dialogocreditos.cpp \
		moc_dialogoajustarprecio.cpp \
		moc_dialogolicencia.cpp \
		moc_instancia.cpp
OBJECTS       = main.o \
		editor.o \
		PrincipalModel.o \
		Calc.o \
		Certificacion.o \
		Concepto.o \
		Datos.o \
		Fecha.o \
		GestorEntradaDatosLineasMedicion.o \
		LineaMedicion.o \
		MedCert.o \
		Medicion.o \
		Obra.o \
		Precio.o \
		Redondeos.o \
		Unidades.o \
		Codificacion.o \
		filter.o \
		tablamedcert.o \
		delegadocolumnasbloqueadas.o \
		tablaprincipal.o \
		iconos.o \
		delegadoiconos.o \
		tablabase.o \
		dialogosuprimirmedicion.o \
		dialogoprecio.o \
		delegadobase.o \
		mainwindow.o \
		dialogodatoscodigoresumen.o \
		dialogonuevacertificacion.o \
		MedCertModel.o \
		undomedicion.o \
		undoeditarprincipal.o \
		micustomtextedit.o \
		delegadonumerosbase.o \
		delegadonumerostablaprincipal.o \
		delegadonumerostablamedcert.o \
		dialogoabout.o \
		dialogocreditos.o \
		dialogoajustarprecio.o \
		undoajustarpresupuesto.o \
		dialogolicencia.o \
		instancia.o \
		abrirguardarseg.o \
		abrirguardarbc3.o \
		abrirguardar.o \
		qrc_iconosEditor.o \
		qrc_iconos.o \
		qrc_recursos.o \
		moc_editor.o \
		moc_filter.o \
		moc_tablamedcert.o \
		moc_delegadocolumnasbloqueadas.o \
		moc_tablaprincipal.o \
		moc_tablabase.o \
		moc_dialogosuprimirmedicion.o \
		moc_dialogoprecio.o \
		moc_delegadobase.o \
		moc_mainwindow.o \
		moc_dialogodatoscodigoresumen.o \
		moc_PrincipalModel.o \
		moc_dialogonuevacertificacion.o \
		moc_MedCertModel.o \
		moc_micustomtextedit.o \
		moc_dialogoabout.o \
		moc_dialogocreditos.o \
		moc_dialogoajustarprecio.o \
		moc_dialogolicencia.o \
		moc_instancia.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++14.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		PruebasInterfazObra.pro Editor/editor.h \
		defs.h \
		Calc/include/Calc.h \
		Calc/include/nodocalc.h \
		Calc/include/pila.h \
		include/arista.h \
		include/Certificacion.h \
		include/Concepto.h \
		include/Datos.h \
		include/definiciones.h \
		include/Fecha.h \
		include/GestorEntradaDatosLineasMedicion.h \
		include/Grafo.h \
		include/Importar.h \
		include/LineaMedicion.h \
		include/MedCert.h \
		include/Medicion.h \
		include/nodo.h \
		include/Obra.h \
		include/Precio.h \
		include/Redondeos.h \
		include/Unidades.h \
		include/Codificacion.h \
		filter.h \
		Tablas/tablamedcert.h \
		Delegados/delegadocolumnasbloqueadas.h \
		Tablas/tablaprincipal.h \
		iconos.h \
		Delegados/delegadoiconos.h \
		Tablas/tablabase.h \
		Dialogos/dialogosuprimirmedicion.h \
		Dialogos/dialogoprecio.h \
		Delegados/delegadobase.h \
		mainwindow.h \
		Dialogos/dialogodatoscodigoresumen.h \
		Modelos/PrincipalModel.h \
		Dialogos/dialogonuevacertificacion.h \
		Modelos/MedCertModel.h \
		Undo/undomedicion.h \
		Undo/undoeditarprincipal.h \
		Editor/micustomtextedit.h \
		Delegados/delegadonumerosbase.h \
		Delegados/delegadonumerostablaprincipal.h \
		Delegados/delegadonumerostablamedcert.h \
		Dialogos/dialogoabout.h \
		Dialogos/dialogocreditos.h \
		Dialogos/dialogoajustarprecio.h \
		Undo/undoajustarpresupuesto.h \
		Dialogos/dialogolicencia.h \
		instancia.h \
		Ficheros/abrirguardarseg.h \
		Ficheros/abrirguardarbc3.h \
		Ficheros/abrirguardar.h main.cpp \
		Editor/editor.cpp \
		Modelos/PrincipalModel.cpp \
		Calc/src/Calc.cpp \
		src/Certificacion.cpp \
		src/Concepto.cpp \
		src/Datos.cpp \
		src/Fecha.cpp \
		src/GestorEntradaDatosLineasMedicion.cpp \
		src/LineaMedicion.cpp \
		src/MedCert.cpp \
		src/Medicion.cpp \
		src/Obra.cpp \
		src/Precio.cpp \
		src/Redondeos.cpp \
		src/Unidades.cpp \
		src/Codificacion.cpp \
		filter.cpp \
		Tablas/tablamedcert.cpp \
		Delegados/delegadocolumnasbloqueadas.cpp \
		Tablas/tablaprincipal.cpp \
		iconos.cpp \
		Delegados/delegadoiconos.cpp \
		Tablas/tablabase.cpp \
		Dialogos/dialogosuprimirmedicion.cpp \
		Dialogos/dialogoprecio.cpp \
		Delegados/delegadobase.cpp \
		mainwindow.cpp \
		Dialogos/dialogodatoscodigoresumen.cpp \
		Dialogos/dialogonuevacertificacion.cpp \
		Modelos/MedCertModel.cpp \
		Undo/undomedicion.cpp \
		Undo/undoeditarprincipal.cpp \
		Editor/micustomtextedit.cpp \
		Delegados/delegadonumerosbase.cpp \
		Delegados/delegadonumerostablaprincipal.cpp \
		Delegados/delegadonumerostablamedcert.cpp \
		Dialogos/dialogoabout.cpp \
		Dialogos/dialogocreditos.cpp \
		Dialogos/dialogoajustarprecio.cpp \
		Undo/undoajustarpresupuesto.cpp \
		Dialogos/dialogolicencia.cpp \
		instancia.cpp \
		Ficheros/abrirguardarseg.cpp \
		Ficheros/abrirguardarbc3.cpp \
		Ficheros/abrirguardar.cpp
QMAKE_TARGET  = SDMed
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = SDMed


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_dialogosuprimirmedicion.h ui_dialogoprecio.h ui_mainwindow.h ui_dialogodatosgenerales.h ui_dialogodatoscodigoresumen.h ui_dialogonuevacertificacion.h ui_editor.h ui_dialogoabout.h ui_dialogocreditos.h ui_dialogoajustarprecio.h ui_dialogolicencia.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PruebasInterfazObra.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++14.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		PruebasInterfazObra.pro \
		Editor/iconosEditor.qrc \
		iconos.qrc \
		recursos.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -config release -o Makefile PruebasInterfazObra.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++14.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
PruebasInterfazObra.pro:
Editor/iconosEditor.qrc:
iconos.qrc:
recursos.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -config release -o Makefile PruebasInterfazObra.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents Editor/iconosEditor.qrc iconos.qrc recursos.qrc $(DISTDIR)/
	$(COPY_FILE) --parents Editor/editor.h defs.h Calc/include/Calc.h Calc/include/nodocalc.h Calc/include/pila.h include/arista.h include/Certificacion.h include/Concepto.h include/Datos.h include/definiciones.h include/Fecha.h include/GestorEntradaDatosLineasMedicion.h include/Grafo.h include/Importar.h include/LineaMedicion.h include/MedCert.h include/Medicion.h include/nodo.h include/Obra.h include/Precio.h include/Redondeos.h include/Unidades.h include/Codificacion.h filter.h Tablas/tablamedcert.h Delegados/delegadocolumnasbloqueadas.h Tablas/tablaprincipal.h iconos.h Delegados/delegadoiconos.h Tablas/tablabase.h Dialogos/dialogosuprimirmedicion.h Dialogos/dialogoprecio.h Delegados/delegadobase.h mainwindow.h Dialogos/dialogodatoscodigoresumen.h Modelos/PrincipalModel.h Dialogos/dialogonuevacertificacion.h Modelos/MedCertModel.h Undo/undomedicion.h Undo/undoeditarprincipal.h Editor/micustomtextedit.h Delegados/delegadonumerosbase.h Delegados/delegadonumerostablaprincipal.h Delegados/delegadonumerostablamedcert.h Dialogos/dialogoabout.h Dialogos/dialogocreditos.h Dialogos/dialogoajustarprecio.h Undo/undoajustarpresupuesto.h Dialogos/dialogolicencia.h instancia.h Ficheros/abrirguardarseg.h Ficheros/abrirguardarbc3.h Ficheros/abrirguardar.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp Editor/editor.cpp Modelos/PrincipalModel.cpp Calc/src/Calc.cpp src/Certificacion.cpp src/Concepto.cpp src/Datos.cpp src/Fecha.cpp src/GestorEntradaDatosLineasMedicion.cpp src/LineaMedicion.cpp src/MedCert.cpp src/Medicion.cpp src/Obra.cpp src/Precio.cpp src/Redondeos.cpp src/Unidades.cpp src/Codificacion.cpp filter.cpp Tablas/tablamedcert.cpp Delegados/delegadocolumnasbloqueadas.cpp Tablas/tablaprincipal.cpp iconos.cpp Delegados/delegadoiconos.cpp Tablas/tablabase.cpp Dialogos/dialogosuprimirmedicion.cpp Dialogos/dialogoprecio.cpp Delegados/delegadobase.cpp mainwindow.cpp Dialogos/dialogodatoscodigoresumen.cpp Dialogos/dialogonuevacertificacion.cpp Modelos/MedCertModel.cpp Undo/undomedicion.cpp Undo/undoeditarprincipal.cpp Editor/micustomtextedit.cpp Delegados/delegadonumerosbase.cpp Delegados/delegadonumerostablaprincipal.cpp Delegados/delegadonumerostablamedcert.cpp Dialogos/dialogoabout.cpp Dialogos/dialogocreditos.cpp Dialogos/dialogoajustarprecio.cpp Undo/undoajustarpresupuesto.cpp Dialogos/dialogolicencia.cpp instancia.cpp Ficheros/abrirguardarseg.cpp Ficheros/abrirguardarbc3.cpp Ficheros/abrirguardar.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Dialogos/dialogosuprimirmedicion.ui Dialogos/dialogoprecio.ui Ui/mainwindow.ui Ui/dialogodatosgenerales.ui Ui/dialogodatoscodigoresumen.ui Ui/dialogonuevacertificacion.ui Editor/editor.ui Dialogos/dialogoabout.ui Dialogos/dialogocreditos.ui Dialogos/dialogoajustarprecio.ui Dialogos/dialogolicencia.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_iconosEditor.cpp qrc_iconos.cpp qrc_recursos.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_iconosEditor.cpp qrc_iconos.cpp qrc_recursos.cpp
qrc_iconosEditor.cpp: Editor/iconosEditor.qrc \
		Editor/iconos/textdocument.png \
		Editor/iconos/color_letra.png \
		Editor/iconos/paste.png \
		Editor/iconos/floppy.png \
		Editor/iconos/alinear_izquierda.png \
		Editor/iconos/copy.png \
		Editor/iconos/centrado.png \
		Editor/iconos/negrita.png \
		Editor/iconos/backward.png \
		Editor/iconos/default.png \
		Editor/iconos/App-package-graphics-icon.png \
		Editor/iconos/opened.png \
		Editor/iconos/alinear_derecha.png \
		Editor/iconos/cursiva.png \
		Editor/iconos/justificar.png \
		Editor/iconos/fuente.png \
		Editor/iconos/color_fondo.png \
		Editor/iconos/cut.png \
		Editor/iconos/forward.png
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name iconosEditor Editor/iconosEditor.qrc -o qrc_iconosEditor.cpp

qrc_iconos.cpp: iconos.qrc \
		Iconos/file.png \
		Iconos/sinclasificar.png \
		Iconos/engineer.png \
		Iconos/brick.png \
		Iconos/delete.png \
		Iconos/trucking.png \
		Iconos/folder.png
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name iconos iconos.qrc -o qrc_iconos.cpp

qrc_recursos.cpp: recursos.qrc \
		images/close.png \
		images/cut.png \
		images/forward.png \
		images/deshacer.png \
		images/floppy.png \
		images/backward.png \
		images/Atras.png \
		images/copy.png \
		images/exit.png \
		images/rehacer.png \
		images/paste.png \
		images/opened.png \
		images/new.png \
		images/Adelante.png
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name recursos recursos.qrc -o qrc_recursos.cpp

compiler_moc_header_make_all: moc_editor.cpp moc_filter.cpp moc_tablamedcert.cpp moc_delegadocolumnasbloqueadas.cpp moc_tablaprincipal.cpp moc_tablabase.cpp moc_dialogosuprimirmedicion.cpp moc_dialogoprecio.cpp moc_delegadobase.cpp moc_mainwindow.cpp moc_dialogodatoscodigoresumen.cpp moc_PrincipalModel.cpp moc_dialogonuevacertificacion.cpp moc_MedCertModel.cpp moc_micustomtextedit.cpp moc_dialogoabout.cpp moc_dialogocreditos.cpp moc_dialogoajustarprecio.cpp moc_dialogolicencia.cpp moc_instancia.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_editor.cpp moc_filter.cpp moc_tablamedcert.cpp moc_delegadocolumnasbloqueadas.cpp moc_tablaprincipal.cpp moc_tablabase.cpp moc_dialogosuprimirmedicion.cpp moc_dialogoprecio.cpp moc_delegadobase.cpp moc_mainwindow.cpp moc_dialogodatoscodigoresumen.cpp moc_PrincipalModel.cpp moc_dialogonuevacertificacion.cpp moc_MedCertModel.cpp moc_micustomtextedit.cpp moc_dialogoabout.cpp moc_dialogocreditos.cpp moc_dialogoajustarprecio.cpp moc_dialogolicencia.cpp moc_instancia.cpp
moc_editor.cpp: ui_editor.h \
		Editor/micustomtextedit.h \
		filter.h \
		Tablas/tablabase.h \
		Delegados/delegadobase.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Delegados/delegadocolumnasbloqueadas.h \
		Delegados/delegadonumerosbase.h \
		Modelos/PrincipalModel.h \
		Dialogos/dialogosuprimirmedicion.h \
		Dialogos/dialogoprecio.h \
		Undo/undoeditarprincipal.h \
		iconos.h \
		Delegados/delegadoiconos.h \
		Delegados/delegadonumerostablaprincipal.h \
		Delegados/delegadonumerostablamedcert.h \
		Modelos/MedCertModel.h \
		Undo/undomedicion.h \
		Editor/editor.h \
		Editor/editor.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/david/programacion/cmasmas/PruebasInterfazObra -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Editor/editor.h -o moc_editor.cpp

moc_filter.cpp: Tablas/tablabase.h \
		Delegados/delegadobase.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Delegados/delegadocolumnasbloqueadas.h \
		Delegados/delegadonumerosbase.h \
		Modelos/PrincipalModel.h \
		Dialogos/dialogosuprimirmedicion.h \
		Dialogos/dialogoprecio.h \
		Undo/undoeditarprincipal.h \
		iconos.h \
		Delegados/delegadoiconos.h \
		Delegados/delegadonumerostablaprincipal.h \
		Delegados/delegadonumerostablamedcert.h \
		Modelos/MedCertModel.h \
		Undo/undomedicion.h \
		filter.h \
		Editor/editor.h \
		ui_editor.h \
		Editor/micustomtextedit.h \
		filter.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/david/programacion/cmasmas/PruebasInterfazObra -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include filter.h -o moc_filter.cpp

moc_tablamedcert.cpp: defs.h \
		Tablas/tablabase.h \
		Delegados/delegadobase.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Delegados/delegadocolumnasbloqueadas.h \
		Delegados/delegadonumerosbase.h \
		Modelos/PrincipalModel.h \
		Dialogos/dialogosuprimirmedicion.h \
		Dialogos/dialogoprecio.h \
		Undo/undoeditarprincipal.h \
		iconos.h \
		Delegados/delegadoiconos.h \
		Delegados/delegadonumerostablaprincipal.h \
		Delegados/delegadonumerostablamedcert.h \
		Modelos/MedCertModel.h \
		Undo/undomedicion.h \
		filter.h \
		Editor/editor.h \
		ui_editor.h \
		Editor/micustomtextedit.h \
		Tablas/tablamedcert.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/david/programacion/cmasmas/PruebasInterfazObra -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Tablas/tablamedcert.h -o moc_tablamedcert.cpp

moc_delegadocolumnasbloqueadas.cpp: Delegados/delegadonumerosbase.h \
		Delegados/delegadobase.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Modelos/PrincipalModel.h \
		Dialogos/dialogosuprimirmedicion.h \
		Dialogos/dialogoprecio.h \
		Undo/undoeditarprincipal.h \
		iconos.h \
		Delegados/delegadocolumnasbloqueadas.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/david/programacion/cmasmas/PruebasInterfazObra -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Delegados/delegadocolumnasbloqueadas.h -o moc_delegadocolumnasbloqueadas.cpp

moc_tablaprincipal.cpp: defs.h \
		Tablas/tablabase.h \
		Delegados/delegadobase.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Delegados/delegadocolumnasbloqueadas.h \
		Delegados/delegadonumerosbase.h \
		Modelos/PrincipalModel.h \
		Dialogos/dialogosuprimirmedicion.h \
		Dialogos/dialogoprecio.h \
		Undo/undoeditarprincipal.h \
		iconos.h \
		Delegados/delegadoiconos.h \
		Delegados/delegadonumerostablaprincipal.h \
		Delegados/delegadonumerostablamedcert.h \
		Modelos/MedCertModel.h \
		Undo/undomedicion.h \
		filter.h \
		Editor/editor.h \
		ui_editor.h \
		Editor/micustomtextedit.h \
		Tablas/tablaprincipal.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/david/programacion/cmasmas/PruebasInterfazObra -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Tablas/tablaprincipal.h -o moc_tablaprincipal.cpp

moc_tablabase.cpp: Delegados/delegadobase.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Delegados/delegadocolumnasbloqueadas.h \
		Delegados/delegadonumerosbase.h \
		Modelos/PrincipalModel.h \
		Dialogos/dialogosuprimirmedicion.h \
		Dialogos/dialogoprecio.h \
		Undo/undoeditarprincipal.h \
		iconos.h \
		Delegados/delegadoiconos.h \
		Delegados/delegadonumerostablaprincipal.h \
		Delegados/delegadonumerostablamedcert.h \
		Modelos/MedCertModel.h \
		Undo/undomedicion.h \
		filter.h \
		Tablas/tablabase.h \
		Editor/editor.h \
		ui_editor.h \
		Editor/micustomtextedit.h \
		Tablas/tablabase.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/david/programacion/cmasmas/PruebasInterfazObra -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Tablas/tablabase.h -o moc_tablabase.cpp

moc_dialogosuprimirmedicion.cpp: Dialogos/dialogosuprimirmedicion.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/david/programacion/cmasmas/PruebasInterfazObra -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Dialogos/dialogosuprimirmedicion.h -o moc_dialogosuprimirmedicion.cpp

moc_dialogoprecio.cpp: defs.h \
		Dialogos/dialogoprecio.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/david/programacion/cmasmas/PruebasInterfazObra -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Dialogos/dialogoprecio.h -o moc_dialogoprecio.cpp

moc_delegadobase.cpp: include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Delegados/delegadobase.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/david/programacion/cmasmas/PruebasInterfazObra -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Delegados/delegadobase.h -o moc_delegadobase.cpp

moc_mainwindow.cpp: instancia.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Ficheros/abrirguardar.h \
		Ficheros/abrirguardarbc3.h \
		Ficheros/abrirguardarseg.h \
		Modelos/PrincipalModel.h \
		Dialogos/dialogosuprimirmedicion.h \
		Dialogos/dialogoprecio.h \
		Undo/undoeditarprincipal.h \
		iconos.h \
		Modelos/MedCertModel.h \
		Undo/undomedicion.h \
		Tablas/tablaprincipal.h \
		Tablas/tablabase.h \
		Delegados/delegadobase.h \
		Delegados/delegadocolumnasbloqueadas.h \
		Delegados/delegadonumerosbase.h \
		Delegados/delegadoiconos.h \
		Delegados/delegadonumerostablaprincipal.h \
		Delegados/delegadonumerostablamedcert.h \
		filter.h \
		Editor/editor.h \
		ui_editor.h \
		Editor/micustomtextedit.h \
		Tablas/tablamedcert.h \
		Undo/undoajustarpresupuesto.h \
		Dialogos/dialogodatoscodigoresumen.h \
		ui_dialogodatoscodigoresumen.h \
		Dialogos/dialogonuevacertificacion.h \
		Dialogos/dialogoajustarprecio.h \
		Dialogos/dialogoabout.h \
		Dialogos/dialogocreditos.h \
		Dialogos/dialogolicencia.h \
		mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/david/programacion/cmasmas/PruebasInterfazObra -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_dialogodatoscodigoresumen.cpp: ui_dialogodatoscodigoresumen.h \
		Dialogos/dialogodatoscodigoresumen.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/david/programacion/cmasmas/PruebasInterfazObra -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Dialogos/dialogodatoscodigoresumen.h -o moc_dialogodatoscodigoresumen.cpp

moc_PrincipalModel.cpp: include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Dialogos/dialogosuprimirmedicion.h \
		Dialogos/dialogoprecio.h \
		Undo/undoeditarprincipal.h \
		Modelos/PrincipalModel.h \
		iconos.h \
		Modelos/PrincipalModel.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/david/programacion/cmasmas/PruebasInterfazObra -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Modelos/PrincipalModel.h -o moc_PrincipalModel.cpp

moc_dialogonuevacertificacion.cpp: Dialogos/dialogonuevacertificacion.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/david/programacion/cmasmas/PruebasInterfazObra -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Dialogos/dialogonuevacertificacion.h -o moc_dialogonuevacertificacion.cpp

moc_MedCertModel.cpp: include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Undo/undomedicion.h \
		Modelos/MedCertModel.h \
		Modelos/MedCertModel.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/david/programacion/cmasmas/PruebasInterfazObra -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Modelos/MedCertModel.h -o moc_MedCertModel.cpp

moc_micustomtextedit.cpp: Editor/micustomtextedit.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/david/programacion/cmasmas/PruebasInterfazObra -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Editor/micustomtextedit.h -o moc_micustomtextedit.cpp

moc_dialogoabout.cpp: Dialogos/dialogocreditos.h \
		Dialogos/dialogolicencia.h \
		Dialogos/dialogoabout.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/david/programacion/cmasmas/PruebasInterfazObra -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Dialogos/dialogoabout.h -o moc_dialogoabout.cpp

moc_dialogocreditos.cpp: Dialogos/dialogocreditos.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/david/programacion/cmasmas/PruebasInterfazObra -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Dialogos/dialogocreditos.h -o moc_dialogocreditos.cpp

moc_dialogoajustarprecio.cpp: Dialogos/dialogoajustarprecio.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/david/programacion/cmasmas/PruebasInterfazObra -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Dialogos/dialogoajustarprecio.h -o moc_dialogoajustarprecio.cpp

moc_dialogolicencia.cpp: Dialogos/dialogolicencia.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/david/programacion/cmasmas/PruebasInterfazObra -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Dialogos/dialogolicencia.h -o moc_dialogolicencia.cpp

moc_instancia.cpp: include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Ficheros/abrirguardar.h \
		Ficheros/abrirguardarbc3.h \
		Ficheros/abrirguardarseg.h \
		Modelos/PrincipalModel.h \
		Dialogos/dialogosuprimirmedicion.h \
		Dialogos/dialogoprecio.h \
		Undo/undoeditarprincipal.h \
		iconos.h \
		Modelos/MedCertModel.h \
		Undo/undomedicion.h \
		Tablas/tablaprincipal.h \
		Tablas/tablabase.h \
		Delegados/delegadobase.h \
		Delegados/delegadocolumnasbloqueadas.h \
		Delegados/delegadonumerosbase.h \
		Delegados/delegadoiconos.h \
		Delegados/delegadonumerostablaprincipal.h \
		Delegados/delegadonumerostablamedcert.h \
		filter.h \
		Editor/editor.h \
		ui_editor.h \
		Editor/micustomtextedit.h \
		Tablas/tablamedcert.h \
		Undo/undoajustarpresupuesto.h \
		instancia.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/david/programacion/cmasmas/PruebasInterfazObra -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include instancia.h -o moc_instancia.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_dialogosuprimirmedicion.h ui_dialogoprecio.h ui_mainwindow.h ui_dialogodatosgenerales.h ui_dialogodatoscodigoresumen.h ui_dialogonuevacertificacion.h ui_editor.h ui_dialogoabout.h ui_dialogocreditos.h ui_dialogoajustarprecio.h ui_dialogolicencia.h
compiler_uic_clean:
	-$(DEL_FILE) ui_dialogosuprimirmedicion.h ui_dialogoprecio.h ui_mainwindow.h ui_dialogodatosgenerales.h ui_dialogodatoscodigoresumen.h ui_dialogonuevacertificacion.h ui_editor.h ui_dialogoabout.h ui_dialogocreditos.h ui_dialogoajustarprecio.h ui_dialogolicencia.h
ui_dialogosuprimirmedicion.h: Dialogos/dialogosuprimirmedicion.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic Dialogos/dialogosuprimirmedicion.ui -o ui_dialogosuprimirmedicion.h

ui_dialogoprecio.h: Dialogos/dialogoprecio.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic Dialogos/dialogoprecio.ui -o ui_dialogoprecio.h

ui_mainwindow.h: Ui/mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic Ui/mainwindow.ui -o ui_mainwindow.h

ui_dialogodatosgenerales.h: Ui/dialogodatosgenerales.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic Ui/dialogodatosgenerales.ui -o ui_dialogodatosgenerales.h

ui_dialogodatoscodigoresumen.h: Ui/dialogodatoscodigoresumen.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic Ui/dialogodatoscodigoresumen.ui -o ui_dialogodatoscodigoresumen.h

ui_dialogonuevacertificacion.h: Ui/dialogonuevacertificacion.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic Ui/dialogonuevacertificacion.ui -o ui_dialogonuevacertificacion.h

ui_editor.h: Editor/editor.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic Editor/editor.ui -o ui_editor.h

ui_dialogoabout.h: Dialogos/dialogoabout.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic Dialogos/dialogoabout.ui -o ui_dialogoabout.h

ui_dialogocreditos.h: Dialogos/dialogocreditos.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic Dialogos/dialogocreditos.ui -o ui_dialogocreditos.h

ui_dialogoajustarprecio.h: Dialogos/dialogoajustarprecio.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic Dialogos/dialogoajustarprecio.ui -o ui_dialogoajustarprecio.h

ui_dialogolicencia.h: Dialogos/dialogolicencia.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic Dialogos/dialogolicencia.ui -o ui_dialogolicencia.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		instancia.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Ficheros/abrirguardar.h \
		Ficheros/abrirguardarbc3.h \
		Ficheros/abrirguardarseg.h \
		Modelos/PrincipalModel.h \
		Dialogos/dialogosuprimirmedicion.h \
		Dialogos/dialogoprecio.h \
		Undo/undoeditarprincipal.h \
		iconos.h \
		Modelos/MedCertModel.h \
		Undo/undomedicion.h \
		Tablas/tablaprincipal.h \
		Tablas/tablabase.h \
		Delegados/delegadobase.h \
		Delegados/delegadocolumnasbloqueadas.h \
		Delegados/delegadonumerosbase.h \
		Delegados/delegadoiconos.h \
		Delegados/delegadonumerostablaprincipal.h \
		Delegados/delegadonumerostablamedcert.h \
		filter.h \
		Editor/editor.h \
		ui_editor.h \
		Editor/micustomtextedit.h \
		Tablas/tablamedcert.h \
		Undo/undoajustarpresupuesto.h \
		Dialogos/dialogodatoscodigoresumen.h \
		ui_dialogodatoscodigoresumen.h \
		Dialogos/dialogonuevacertificacion.h \
		Dialogos/dialogoajustarprecio.h \
		Dialogos/dialogoabout.h \
		Dialogos/dialogocreditos.h \
		Dialogos/dialogolicencia.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

editor.o: Editor/editor.cpp Editor/editor.h \
		ui_editor.h \
		Editor/micustomtextedit.h \
		filter.h \
		Tablas/tablabase.h \
		Delegados/delegadobase.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Delegados/delegadocolumnasbloqueadas.h \
		Delegados/delegadonumerosbase.h \
		Modelos/PrincipalModel.h \
		Dialogos/dialogosuprimirmedicion.h \
		Dialogos/dialogoprecio.h \
		Undo/undoeditarprincipal.h \
		iconos.h \
		Delegados/delegadoiconos.h \
		Delegados/delegadonumerostablaprincipal.h \
		Delegados/delegadonumerostablamedcert.h \
		Modelos/MedCertModel.h \
		Undo/undomedicion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editor.o Editor/editor.cpp

PrincipalModel.o: Modelos/PrincipalModel.cpp Modelos/PrincipalModel.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Dialogos/dialogosuprimirmedicion.h \
		Dialogos/dialogoprecio.h \
		Undo/undoeditarprincipal.h \
		iconos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PrincipalModel.o Modelos/PrincipalModel.cpp

Calc.o: Calc/src/Calc.cpp Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Calc.o Calc/src/Calc.cpp

Certificacion.o: src/Certificacion.cpp include/Certificacion.h \
		include/Fecha.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Certificacion.o src/Certificacion.cpp

Concepto.o: src/Concepto.cpp include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Concepto.o src/Concepto.cpp

Datos.o: src/Datos.cpp include/Datos.h \
		include/Fecha.h \
		include/Concepto.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Datos.o src/Datos.cpp

Fecha.o: src/Fecha.cpp include/Fecha.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Fecha.o src/Fecha.cpp

GestorEntradaDatosLineasMedicion.o: src/GestorEntradaDatosLineasMedicion.cpp include/GestorEntradaDatosLineasMedicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GestorEntradaDatosLineasMedicion.o src/GestorEntradaDatosLineasMedicion.cpp

LineaMedicion.o: src/LineaMedicion.cpp include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LineaMedicion.o src/LineaMedicion.cpp

MedCert.o: src/MedCert.cpp include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		include/Fecha.h \
		defs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MedCert.o src/MedCert.cpp

Medicion.o: src/Medicion.cpp include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		include/Fecha.h \
		defs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Medicion.o src/Medicion.cpp

Obra.o: src/Obra.cpp include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Obra.o src/Obra.cpp

Precio.o: src/Precio.cpp include/Precio.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Precio.o src/Precio.cpp

Redondeos.o: src/Redondeos.cpp include/Redondeos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Redondeos.o src/Redondeos.cpp

Unidades.o: src/Unidades.cpp include/Unidades.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Unidades.o src/Unidades.cpp

Codificacion.o: src/Codificacion.cpp include/Codificacion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Codificacion.o src/Codificacion.cpp

filter.o: filter.cpp filter.h \
		Tablas/tablabase.h \
		Delegados/delegadobase.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Delegados/delegadocolumnasbloqueadas.h \
		Delegados/delegadonumerosbase.h \
		Modelos/PrincipalModel.h \
		Dialogos/dialogosuprimirmedicion.h \
		Dialogos/dialogoprecio.h \
		Undo/undoeditarprincipal.h \
		iconos.h \
		Delegados/delegadoiconos.h \
		Delegados/delegadonumerostablaprincipal.h \
		Delegados/delegadonumerostablamedcert.h \
		Modelos/MedCertModel.h \
		Undo/undomedicion.h \
		Editor/editor.h \
		ui_editor.h \
		Editor/micustomtextedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filter.o filter.cpp

tablamedcert.o: Tablas/tablamedcert.cpp Tablas/tablamedcert.h \
		defs.h \
		Tablas/tablabase.h \
		Delegados/delegadobase.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Delegados/delegadocolumnasbloqueadas.h \
		Delegados/delegadonumerosbase.h \
		Modelos/PrincipalModel.h \
		Dialogos/dialogosuprimirmedicion.h \
		Dialogos/dialogoprecio.h \
		Undo/undoeditarprincipal.h \
		iconos.h \
		Delegados/delegadoiconos.h \
		Delegados/delegadonumerostablaprincipal.h \
		Delegados/delegadonumerostablamedcert.h \
		Modelos/MedCertModel.h \
		Undo/undomedicion.h \
		filter.h \
		Editor/editor.h \
		ui_editor.h \
		Editor/micustomtextedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tablamedcert.o Tablas/tablamedcert.cpp

delegadocolumnasbloqueadas.o: Delegados/delegadocolumnasbloqueadas.cpp Delegados/delegadocolumnasbloqueadas.h \
		Delegados/delegadonumerosbase.h \
		Delegados/delegadobase.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Modelos/PrincipalModel.h \
		Dialogos/dialogosuprimirmedicion.h \
		Dialogos/dialogoprecio.h \
		Undo/undoeditarprincipal.h \
		iconos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o delegadocolumnasbloqueadas.o Delegados/delegadocolumnasbloqueadas.cpp

tablaprincipal.o: Tablas/tablaprincipal.cpp Tablas/tablaprincipal.h \
		defs.h \
		Tablas/tablabase.h \
		Delegados/delegadobase.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Delegados/delegadocolumnasbloqueadas.h \
		Delegados/delegadonumerosbase.h \
		Modelos/PrincipalModel.h \
		Dialogos/dialogosuprimirmedicion.h \
		Dialogos/dialogoprecio.h \
		Undo/undoeditarprincipal.h \
		iconos.h \
		Delegados/delegadoiconos.h \
		Delegados/delegadonumerostablaprincipal.h \
		Delegados/delegadonumerostablamedcert.h \
		Modelos/MedCertModel.h \
		Undo/undomedicion.h \
		filter.h \
		Editor/editor.h \
		ui_editor.h \
		Editor/micustomtextedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tablaprincipal.o Tablas/tablaprincipal.cpp

iconos.o: iconos.cpp iconos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iconos.o iconos.cpp

delegadoiconos.o: Delegados/delegadoiconos.cpp Delegados/delegadoiconos.h \
		Delegados/delegadobase.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		iconos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o delegadoiconos.o Delegados/delegadoiconos.cpp

tablabase.o: Tablas/tablabase.cpp Tablas/tablabase.h \
		Delegados/delegadobase.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Delegados/delegadocolumnasbloqueadas.h \
		Delegados/delegadonumerosbase.h \
		Modelos/PrincipalModel.h \
		Dialogos/dialogosuprimirmedicion.h \
		Dialogos/dialogoprecio.h \
		Undo/undoeditarprincipal.h \
		iconos.h \
		Delegados/delegadoiconos.h \
		Delegados/delegadonumerostablaprincipal.h \
		Delegados/delegadonumerostablamedcert.h \
		Modelos/MedCertModel.h \
		Undo/undomedicion.h \
		filter.h \
		Editor/editor.h \
		ui_editor.h \
		Editor/micustomtextedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tablabase.o Tablas/tablabase.cpp

dialogosuprimirmedicion.o: Dialogos/dialogosuprimirmedicion.cpp Dialogos/dialogosuprimirmedicion.h \
		ui_dialogosuprimirmedicion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogosuprimirmedicion.o Dialogos/dialogosuprimirmedicion.cpp

dialogoprecio.o: Dialogos/dialogoprecio.cpp Dialogos/dialogoprecio.h \
		defs.h \
		ui_dialogoprecio.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogoprecio.o Dialogos/dialogoprecio.cpp

delegadobase.o: Delegados/delegadobase.cpp Delegados/delegadobase.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o delegadobase.o Delegados/delegadobase.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		instancia.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Ficheros/abrirguardar.h \
		Ficheros/abrirguardarbc3.h \
		Ficheros/abrirguardarseg.h \
		Modelos/PrincipalModel.h \
		Dialogos/dialogosuprimirmedicion.h \
		Dialogos/dialogoprecio.h \
		Undo/undoeditarprincipal.h \
		iconos.h \
		Modelos/MedCertModel.h \
		Undo/undomedicion.h \
		Tablas/tablaprincipal.h \
		Tablas/tablabase.h \
		Delegados/delegadobase.h \
		Delegados/delegadocolumnasbloqueadas.h \
		Delegados/delegadonumerosbase.h \
		Delegados/delegadoiconos.h \
		Delegados/delegadonumerostablaprincipal.h \
		Delegados/delegadonumerostablamedcert.h \
		filter.h \
		Editor/editor.h \
		ui_editor.h \
		Editor/micustomtextedit.h \
		Tablas/tablamedcert.h \
		Undo/undoajustarpresupuesto.h \
		Dialogos/dialogodatoscodigoresumen.h \
		ui_dialogodatoscodigoresumen.h \
		Dialogos/dialogonuevacertificacion.h \
		Dialogos/dialogoajustarprecio.h \
		Dialogos/dialogoabout.h \
		Dialogos/dialogocreditos.h \
		Dialogos/dialogolicencia.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

dialogodatoscodigoresumen.o: Dialogos/dialogodatoscodigoresumen.cpp Dialogos/dialogodatoscodigoresumen.h \
		ui_dialogodatoscodigoresumen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogodatoscodigoresumen.o Dialogos/dialogodatoscodigoresumen.cpp

dialogonuevacertificacion.o: Dialogos/dialogonuevacertificacion.cpp Dialogos/dialogonuevacertificacion.h \
		ui_dialogonuevacertificacion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogonuevacertificacion.o Dialogos/dialogonuevacertificacion.cpp

MedCertModel.o: Modelos/MedCertModel.cpp Modelos/MedCertModel.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Undo/undomedicion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MedCertModel.o Modelos/MedCertModel.cpp

undomedicion.o: Undo/undomedicion.cpp Undo/undomedicion.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Modelos/MedCertModel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o undomedicion.o Undo/undomedicion.cpp

undoeditarprincipal.o: Undo/undoeditarprincipal.cpp Undo/undoeditarprincipal.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Modelos/PrincipalModel.h \
		Dialogos/dialogosuprimirmedicion.h \
		Dialogos/dialogoprecio.h \
		iconos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o undoeditarprincipal.o Undo/undoeditarprincipal.cpp

micustomtextedit.o: Editor/micustomtextedit.cpp Editor/micustomtextedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o micustomtextedit.o Editor/micustomtextedit.cpp

delegadonumerosbase.o: Delegados/delegadonumerosbase.cpp Delegados/delegadonumerosbase.h \
		Delegados/delegadobase.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Modelos/PrincipalModel.h \
		Dialogos/dialogosuprimirmedicion.h \
		Dialogos/dialogoprecio.h \
		Undo/undoeditarprincipal.h \
		iconos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o delegadonumerosbase.o Delegados/delegadonumerosbase.cpp

delegadonumerostablaprincipal.o: Delegados/delegadonumerostablaprincipal.cpp Delegados/delegadonumerostablaprincipal.h \
		Delegados/delegadonumerosbase.h \
		Delegados/delegadobase.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Modelos/PrincipalModel.h \
		Dialogos/dialogosuprimirmedicion.h \
		Dialogos/dialogoprecio.h \
		Undo/undoeditarprincipal.h \
		iconos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o delegadonumerostablaprincipal.o Delegados/delegadonumerostablaprincipal.cpp

delegadonumerostablamedcert.o: Delegados/delegadonumerostablamedcert.cpp Delegados/delegadonumerostablamedcert.h \
		Delegados/delegadonumerosbase.h \
		Delegados/delegadobase.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Modelos/PrincipalModel.h \
		Dialogos/dialogosuprimirmedicion.h \
		Dialogos/dialogoprecio.h \
		Undo/undoeditarprincipal.h \
		iconos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o delegadonumerostablamedcert.o Delegados/delegadonumerostablamedcert.cpp

dialogoabout.o: Dialogos/dialogoabout.cpp Dialogos/dialogoabout.h \
		Dialogos/dialogocreditos.h \
		Dialogos/dialogolicencia.h \
		ui_dialogoabout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogoabout.o Dialogos/dialogoabout.cpp

dialogocreditos.o: Dialogos/dialogocreditos.cpp Dialogos/dialogocreditos.h \
		ui_dialogocreditos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogocreditos.o Dialogos/dialogocreditos.cpp

dialogoajustarprecio.o: Dialogos/dialogoajustarprecio.cpp Dialogos/dialogoajustarprecio.h \
		ui_dialogoajustarprecio.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogoajustarprecio.o Dialogos/dialogoajustarprecio.cpp

undoajustarpresupuesto.o: Undo/undoajustarpresupuesto.cpp Undo/undoajustarpresupuesto.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o undoajustarpresupuesto.o Undo/undoajustarpresupuesto.cpp

dialogolicencia.o: Dialogos/dialogolicencia.cpp Dialogos/dialogolicencia.h \
		ui_dialogolicencia.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogolicencia.o Dialogos/dialogolicencia.cpp

instancia.o: instancia.cpp instancia.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h \
		Ficheros/abrirguardar.h \
		Ficheros/abrirguardarbc3.h \
		Ficheros/abrirguardarseg.h \
		Modelos/PrincipalModel.h \
		Dialogos/dialogosuprimirmedicion.h \
		Dialogos/dialogoprecio.h \
		Undo/undoeditarprincipal.h \
		iconos.h \
		Modelos/MedCertModel.h \
		Undo/undomedicion.h \
		Tablas/tablaprincipal.h \
		Tablas/tablabase.h \
		Delegados/delegadobase.h \
		Delegados/delegadocolumnasbloqueadas.h \
		Delegados/delegadonumerosbase.h \
		Delegados/delegadoiconos.h \
		Delegados/delegadonumerostablaprincipal.h \
		Delegados/delegadonumerostablamedcert.h \
		filter.h \
		Editor/editor.h \
		ui_editor.h \
		Editor/micustomtextedit.h \
		Tablas/tablamedcert.h \
		Undo/undoajustarpresupuesto.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o instancia.o instancia.cpp

abrirguardarseg.o: Ficheros/abrirguardarseg.cpp Ficheros/abrirguardarseg.h \
		Ficheros/abrirguardar.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o abrirguardarseg.o Ficheros/abrirguardarseg.cpp

abrirguardarbc3.o: Ficheros/abrirguardarbc3.cpp Ficheros/abrirguardarbc3.h \
		Ficheros/abrirguardar.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o abrirguardarbc3.o Ficheros/abrirguardarbc3.cpp

abrirguardar.o: Ficheros/abrirguardar.cpp Ficheros/abrirguardar.h \
		include/Obra.h \
		include/Grafo.h \
		include/arista.h \
		include/nodo.h \
		include/definiciones.h \
		include/Concepto.h \
		include/Fecha.h \
		include/Codificacion.h \
		include/Precio.h \
		include/Unidades.h \
		include/MedCert.h \
		include/Medicion.h \
		include/LineaMedicion.h \
		Calc/include/Calc.h \
		Calc/include/pila.h \
		Calc/include/nodocalc.h \
		include/GestorEntradaDatosLineasMedicion.h \
		defs.h \
		include/Redondeos.h \
		include/Certificacion.h \
		include/Datos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o abrirguardar.o Ficheros/abrirguardar.cpp

qrc_iconosEditor.o: qrc_iconosEditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_iconosEditor.o qrc_iconosEditor.cpp

qrc_iconos.o: qrc_iconos.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_iconos.o qrc_iconos.cpp

qrc_recursos.o: qrc_recursos.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_recursos.o qrc_recursos.cpp

moc_editor.o: moc_editor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editor.o moc_editor.cpp

moc_filter.o: moc_filter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filter.o moc_filter.cpp

moc_tablamedcert.o: moc_tablamedcert.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tablamedcert.o moc_tablamedcert.cpp

moc_delegadocolumnasbloqueadas.o: moc_delegadocolumnasbloqueadas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_delegadocolumnasbloqueadas.o moc_delegadocolumnasbloqueadas.cpp

moc_tablaprincipal.o: moc_tablaprincipal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tablaprincipal.o moc_tablaprincipal.cpp

moc_tablabase.o: moc_tablabase.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tablabase.o moc_tablabase.cpp

moc_dialogosuprimirmedicion.o: moc_dialogosuprimirmedicion.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialogosuprimirmedicion.o moc_dialogosuprimirmedicion.cpp

moc_dialogoprecio.o: moc_dialogoprecio.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialogoprecio.o moc_dialogoprecio.cpp

moc_delegadobase.o: moc_delegadobase.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_delegadobase.o moc_delegadobase.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_dialogodatoscodigoresumen.o: moc_dialogodatoscodigoresumen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialogodatoscodigoresumen.o moc_dialogodatoscodigoresumen.cpp

moc_PrincipalModel.o: moc_PrincipalModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PrincipalModel.o moc_PrincipalModel.cpp

moc_dialogonuevacertificacion.o: moc_dialogonuevacertificacion.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialogonuevacertificacion.o moc_dialogonuevacertificacion.cpp

moc_MedCertModel.o: moc_MedCertModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MedCertModel.o moc_MedCertModel.cpp

moc_micustomtextedit.o: moc_micustomtextedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_micustomtextedit.o moc_micustomtextedit.cpp

moc_dialogoabout.o: moc_dialogoabout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialogoabout.o moc_dialogoabout.cpp

moc_dialogocreditos.o: moc_dialogocreditos.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialogocreditos.o moc_dialogocreditos.cpp

moc_dialogoajustarprecio.o: moc_dialogoajustarprecio.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialogoajustarprecio.o moc_dialogoajustarprecio.cpp

moc_dialogolicencia.o: moc_dialogolicencia.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialogolicencia.o moc_dialogolicencia.cpp

moc_instancia.o: moc_instancia.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_instancia.o moc_instancia.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

